version: "3.8"

services:
  database:
    container_name: ${CONTAINER_BASENAME}_database
    image: mariadb:jammy
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  php:
    container_name: ${CONTAINER_BASENAME}_php
    image: ${TAG_BASENAME}_php
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - assets:/var/www/html/_assets/
      - chevereto:/var/www/html/
      - type: bind
        source: ${SOURCE}
        target: /var/www/chevereto
      - type: bind
        source: ${PWD}/.well-known
        target: /var/www/html/.well-known
      - type: bind
        source: ${PWD}/${HTTPS_CERT}
        target: /etc/ssl/certs/cert.pem
      - type: bind
        source: ${PWD}/${HTTPS_KEY}
        target: /etc/ssl/private/key.pem

    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    restart: always
    environment:
      CHEVERETO_TAG: dev
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HOSTNAME: ${HOSTNAME}
      CHEVERETO_HOSTNAME_PATH: ${HOSTNAME_PATH}
      CHEVERETO_HTTPS: ${HTTPS}
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: ${URL}_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/_assets/
      CHEVERETO_ENCRYPTION_KEY: yUwfiRh6anwqC/sIx3COCIZeMT9rxdbXkMDdfgyrM2M=

volumes:
  database:
  assets:
  storage:
  chevereto:

networks:
  chevereto:
