services:
  database:
    container_name: ${CONTAINER_BASENAME}_database
    image: mysql
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    healthcheck:
      # test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"] # MariaDB
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"] # MySQL
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  php:
    container_name: ${CONTAINER_BASENAME}_php
    image: ${IMAGE}
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - chevereto:/var/www/html/
      - type: bind
        source: ${SOURCE}
        target: /var/www/chevereto
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      CHEVERETO_ENVIRONMENT: dev
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HOSTNAME: ${HOSTNAME}
      CHEVERETO_HOSTNAME_PATH: ${HOSTNAME_PATH}
      CHEVERETO_HTTPS: ${HTTPS}
      CHEVERETO_ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      CHEVERETO_MAX_POST_SIZE: 2G
      CHEVERETO_MAX_UPLOAD_SIZE: 2G

volumes:
  database:
  storage:
  chevereto:

networks:
  chevereto:
